name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
autolabeler:
  - label: 'feature'
    title:
      - '/^feat/i'
      - '/^add/i'
  - label: 'bug'
    title:
      - '/^fix/i'
      - '/^bug/i'
  - label: 'chore'
    title:
      - '/^chore/i'
      - '/^refactor/i'
      - '/^update/i'
      - '/^improve/i'
  - label: 'documentation'
    title:
      - '/^docs/i'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'dependencies'
  - title: '📚 Documentation'
    labels:
      - 'documentation'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes

  $CHANGES

  ## Test Checklist (gianism.info)

  Before publishing this release, please test the following on https://gianism.info:

  - [ ] Site loads without errors (white screen check)
  - [ ] Plugin is active and working
  - [ ] Facebook login works
  - [ ] Twitter login works (if enabled)
  - [ ] Google login works (if enabled)
  - [ ] User account connection/disconnection works
  - [ ] Admin settings page loads and saves correctly

  ## Deploy Instructions

  1. Test on gianism.info (already deployed from master)
  2. Complete the checklist above
  3. If all tests pass, publish this release
  4. Publishing will trigger automatic deployment to WordPress.org
