name: Release Publish

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  create-tag:
    name: Create Tag and Trigger Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract version from release
        id: extract_version
        run: |
          VERSION=${{ github.event.release.tag_name }}
          # Remove 'v' prefix if it exists
          VERSION=${VERSION#v}
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create and push tag
        run: |
          VERSION=${{ steps.extract_version.outputs.version }}
          # Check if tag already exists
          if git rev-parse "v${VERSION}" >/dev/null 2>&1; then
            echo "Tag v${VERSION} already exists"
          else
            git tag "v${VERSION}"
            git push origin "v${VERSION}"
            echo "Created and pushed tag v${VERSION}"
          fi